name: Pipeline de Scraping Quotidien

on:
  schedule:
    - cron: '30 1 * * *' 
  workflow_dispatch:

jobs:
  run-daily-scraping:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout du code
        uses: actions/checkout@v4

      - name: 🐍 Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 🌐 Installation de Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: 📦 Installation des dépendances Python
        run: |
          # 1. Mise à jour de pip
          python -m pip install --upgrade pip
          # 2. Installation de toutes les librairies, y compris boto3
          pip install -r requirements.txt
          
      - name: ⚙️ Exécution du pipeline principal
        working-directory: ./scraping_lois/ 
        run: python main_pipeline_scraping.py
        env:
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
